ALTER TABLE activity_task ADD COLUMN claimed_epoch INTEGER;
ALTER TABLE activity_task ADD COLUMN attempt INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_task ADD COLUMN available_utc_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_task ADD COLUMN scheduled_utc_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_task ADD COLUMN started_utc_ms INTEGER;
ALTER TABLE activity_task ADD COLUMN heartbeat_utc_ms INTEGER;
ALTER TABLE activity_task ADD COLUMN deadline_utc_ms INTEGER;
ALTER TABLE activity_task ADD COLUMN schema_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_task ADD COLUMN schema_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE activity_task ADD COLUMN status_v2 TEXT NOT NULL DEFAULT 'ready' CHECK(status_v2 IN ('ready','claimed','completed'));
CREATE INDEX activity_task_ready_idx ON activity_task(status_v2, available_utc_ms, task_id);
ALTER TABLE durable_timer ADD COLUMN claimed_epoch INTEGER;
ALTER TABLE durable_timer ADD COLUMN schema_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE durable_timer ADD COLUMN schema_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE durable_timer ADD COLUMN status_v2 TEXT NOT NULL DEFAULT 'ready' CHECK(status_v2 IN ('ready','claimed','completed'));
CREATE INDEX durable_timer_ready_v2_idx ON durable_timer(status_v2, fire_at_utc_ms, timer_id);
ALTER TABLE outbox ADD COLUMN claimed_epoch INTEGER;
ALTER TABLE outbox ADD COLUMN status_v2 TEXT NOT NULL DEFAULT 'ready' CHECK(status_v2 IN ('ready','claimed','completed'));
CREATE INDEX outbox_ready_v2_idx ON outbox(status_v2, message_id);
